config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy] do
   member do
    post :confirm
   end
  end

  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

   root 'top#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  mount_uploader :gazou
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader
  has_many :posts

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

   # before_actionで下で定義したメソッドを実行
   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
   PERMISSIBLE_ATTRIBUTES = %i(name)

   protected

     #deviseのストロングパラメーターにカラム追加するメソッドを定義
     def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
       devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
   @posts = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(posts_params)
    else
      @post = Post.new
    end
  end

  def create
   @post = Post.new(posts_params)
   @post.user_id = current_user.id
   if @post.save
    redirect_to posts_path, notice: "投稿しました！"
    NoticeMailer.sendmail_post(@post).deliver
   else
    render'new'
   end
  end

  def show
  end

  def edit
   @post = Post.find(params[:id])
  end

  def update
   @post = Post.find(params[:id])

   if @post.update(posts_params)
     redirect_to posts_path, notice: "投稿内容を編集しました！"
    else
     render 'edit'
   end
  end

  def destroy
   @post = Post.find(params[:id])
   @post.destroy
   redirect_to posts_path, notice: "投稿内容を削除しました！"
  end

  def confirm
   @post = Post.new(posts_params)
   render :new if @post.invalid?
  end

 private
   def posts_params
    params.require(:post).permit(:title, :content, :gazou)
   end

   def set_post
    @post = Post.find(params[:id])
   end
 end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
   # You need to implement the method below in your model
   @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

   if @user.persisted?
     set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
     sign_in_and_redirect @user, event: :authentication
   else
     session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
     redirect_to new_user_registration_url
   end
 end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
    elsif action_name == 'edit'
     post_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daikadai2</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "投稿一覧", posts_path %></li>
      <li><%= link_to "投稿する", new_post_path %></li>
    <% if user_signed_in? %>
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to 'ログイン', new_user_session_path %></li>
     <li><%= link_to 'サインアップ', new_user_registration_path %></li>
    <% end %>
   </ul>
  </header>
<%= yield %>
  <footer>
    <p>instagram風アプリ</p>
  </footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, url: choose_new_or_edit) do |f| %>
<% if @post.errors.any? %>
 <div id="error_explanation">
  <h2><%= @post.errors.count %>件のエラーがあります。</h2>

  <ul>
  <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
  <% end %>
　</ul>
 </div>
<% end %>

  <%= f.label "タイトル" %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label "コメント" %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%=f.label "画像" %>
  <%= f.file_field :gazou, class: 'form-control' %>

  <%= f.submit class: 'btn btn-primary btn-block' %>

<% end %>

<%= link_to "投稿一覧画面にもどる", posts_path, class: 'btn btn-primary btn-block' %>

app/views/posts/confirm.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>
<%= form_for(@poem) do |f| %>
 <%= f.hidden_field :title %>
 <%= f.hidden_field :content %>
 <p>タイトル:<%= @poem.title %></p>
 <p>コメント:<%= @poem.content %></p>
 <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
<% end %>
<%= form_for(@post, url: new_post_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name:'back', class: 'btn btn-primary btn-block' %>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h2>投稿内容を編集する</h2>
<%= render 'form' %>
</div>
</div>

app/views/posts/index.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p><%= notice %></p>
<h1>投稿一覧</h1>
<p><%= link_to "投稿する", new_post_path, class: 'btn btn-default' %></p>
<% @posts.each do |post| %>
<div class="row">
 <h4><strog><p>タイトル:<%= post.title %></p></strog></h4>
 <p>コメント:<%= post.content %></p>
 <p>画像:<img src="<%= post.gazou %>" class="img-responsive center-block"></p>
 <p>ユーザー:<%= post.user.name %></p>
 <%= link_to "投稿内容を編集する", edit_post_path(post.id), class: 'btn btn-default btn-sm btn-success' %>
 <%= link_to '投稿内容を削除する', post_path(post.id), method: :delete, data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-default btn-sm btn-success'  %>
</div>
<div id="page-top-btn" class="page-top-btn">
 <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p id="notice"><%= notice %></p>
<h2>投稿する</h2>
<%= render 'form' %>
</div>
</div>

app/views/top/index.html.erb
<section class="main-header">
  <p class="flash"><%= notice %><%= alert %></p>
</section>
  <div class="row">
  <h1>大課題2のinstagramっぽいアプリ</h1>
  <p>大課題2のために作られた写真投稿するためのアプリのトップページです</p>
      <img src="<%= asset_path "ぬこ.jpg" %>" class="img-responsive center-block">
  </div>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>
</section>